services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      # - /etc/letsencrypt:/etc/letsencrypt:ro  # 호스트에서 cert 관리
      - ./data/certbot/conf:/etc/letsencrypt # certbot의 인증서 저장소
      - ./data/certbot/www:/var/www/certbot # wellknown challenge를 위한 경로
    depends_on:
      - web
      - bff
      - certbot
    networks:
      - prod-net
      - nginx_network
    profiles:
      - prod

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: > 
      /bin/sh -c "trap exit TERM; 
      while :; do 
        certbot renew --deploy-hook 'docker exec nginx nginx -s reload'; 
        sleep 12h & wait $${!}; 
      done;"
    networks:
      - nginx_network
    profiles:
      - prod

  web:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.web
    container_name: front
    expose:
      - "3000"
    image: yyoooonn/yyoooonnweb:v0.0.0
    platform: linux/amd64
    networks:
      - prod-net
    profiles:
      - prod

  bff:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.bff
    environment:
      - NODE_ENV=production
    container_name: back
    image: yyoooonn/yyoooonnbff:v0.0.0
    platform: linux/amd64
    expose:
      - "4000"
    networks:
      - prod-net
    profiles:
      - prod

  postgres:
    platform: linux/amd64
    image: postgres:15
    container_name: db
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgres/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 3s
      timeout: 3s
      retries: 10
    profiles:
      - db

volumes:
  pgdata:

networks:
  prod-net:
  nginx_network: