services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - bff
    networks:
      - dev-net
    extra_hosts:
      - "localhost:127.0.0.1"
      - "api.localhost:127.0.0.1"
    profiles:
      - test

  web:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.web
    container_name: front
    expose:
      - "3000"
    networks:
      - dev-net
    profiles:
      - test
      - local

  bff:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.bff
    container_name: back
    expose:
      - "4000"
    networks:
      - dev-net
    profiles:
      - test
      - local

  postgres:
    platform: linux/amd64
    image: postgres:15
    container_name: db
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgres/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 3s
      timeout: 3s
      retries: 10
    profiles:
      - db

volumes:
  pgdata:

networks:
  dev-net: