services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - bff
    networks:
      - dev-net
    extra_hosts:
      - "localhost:127.0.0.1"
      - "api.localhost:127.0.0.1"
    profiles:
      - test

  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - NEXT_PUBLIC_GRAPHQL_API=${NEXT_PUBLIC_GRAPHQL_API}
    environment:
      - NEXT_PUBLIC_GRAPHQL_API=${NEXT_PUBLIC_GRAPHQL_API}
    container_name: front
    expose:
      - "3000"
    networks:
      - dev-net
    profiles:
      - test
      - local

  bff:
    env_file:
      - .env
    build:
      context: .
      dockerfile: apps/bff/Dockerfile
    environment:
      - NODE_ENV=production # graphql 파일 라우팅 때문에 필요
    container_name: back
    expose:
      - "4000"
    networks:
      - dev-net
    profiles:
      - test
      - local
      - back

  # postgres:
  #   platform: linux/amd64
  #   image: postgres:15
  #   container_name: db
  #   restart: always
  #   ports:
  #     - ${POSTGRES_PORT}:5432
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   volumes:
  #     - pgdata:/var/lib/postgres/data
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "user"]
  #     interval: 3s
  #     timeout: 3s
  #     retries: 10
  #   profiles:
  #     - db

  redis:
    image: redis:7-alpine
    container_name: redis
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    command: >
      sh -c "redis-server --requirepass $${REDIS_PASSWORD} --maxmemory $${MAX_MEMORY} --appendonly yes"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - dev-net
    profiles:
      - test
      - db
      - back

volumes:
  redis-data:
  # pgdata:

networks:
  dev-net: