services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      # - /etc/letsencrypt:/etc/letsencrypt:ro  # 호스트에서 cert 관리
      - ./data/certbot/conf:/etc/letsencrypt # certbot의 인증서 저장소
      - ./data/certbot/www:/var/www/certbot # wellknown challenge를 위한 경로
    depends_on:
      - web
      - bff
      - certbot
    networks:
      - prod-net
      - nginx_network
    profiles:
      - prod
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: >
      /bin/sh -c "apk add docker-cli && trap exit TERM;
      while :; do
        certbot renew --deploy-hook 'docker exec nginx nginx -s reload';
        sleep 12h & wait $${!};
      done;"
    networks:
      - nginx_network
    profiles:
      - prod

  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        - NEXT_PUBLIC_GRAPHQL_API=${NEXT_PUBLIC_GRAPHQL_API}
    environment:
      - NEXT_PUBLIC_GRAPHQL_API=${NEXT_PUBLIC_GRAPHQL_API}
    container_name: front
    expose:
      - "3000"
    image: yyoooonn/yyoooonnweb:v0.0.0
    platform: linux/amd64
    networks:
      - prod-net
    profiles:
      - prod

  bff:
    env_file:
      - .env
    build:
      context: .
      dockerfile: apps/bff/Dockerfile
    environment:
      - NODE_ENV=production
    container_name: back
    image: yyoooonn/yyoooonnbff:v0.0.0
    platform: linux/amd64
    expose:
      - "4000"
    networks:
      - prod-net
    depends_on:
      - redis
    profiles:
      - prod
  redis:
    image: redis:7-alpine
    container_name: redis
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    command: >
      sh -c "redis-server --requirepass $${REDIS_PASSWORD} --maxmemory $${MAX_MEMORY} --appendonly yes"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - prod-net
    profiles:
      - prod

volumes:
  redis-data:

networks:
  prod-net:
  nginx_network: