services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # 호스트에서 cert 관리
    depends_on:
      - front
      - back
    networks:
      - prod-net
    profiles:
      -prod

  web:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.web
    container_name: front
    expose:
      - "3000"
    networks:
      - prod-net
    profiles:
      -prod

  bff:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile.bff
    container_name: back
    expose:
      - "8080"
    networks:
      - prod-net
    profiles:
      -prod

  postgres:
    platform: linux/amd64
    image: postgres:15
    container_name: db
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgres/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 3s
      timeout: 3s
      retries: 10
    profiles:
      - db

volumes:
  pgdata:

networks:
  prod-net: